[tool.poetry]
name = "pyslc-service"
version = "0.1.0"
description = ""
authors = ["Tín Đặng <tindang.ht97@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11, <3.12"
fastapi = "^0.109.0"
sqlalchemy = "^2.0.25"
alembic = "^1.13.1"
pydantic = "^2.5.3"
pydantic-settings = "^2.1.0"
openai = "^1.7.2"
uvicorn = "^0.25.0"
llama-index = "^0.9.35"
zep-python = "^1.5.0"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
