"""init database

Revision ID: dce839d12459
Revises:
Create Date: 2024-03-28 17:52:53.461916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dce839d12459"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_collection")),
        schema="pyslc",
    )
    op.create_index(
        op.f("ix_pyslc_collection_name"),
        "collection",
        ["name"],
        unique=False,
        schema="pyslc",
    )
    op.create_table(
        "chat",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("collection_uid", sa.UUID(), nullable=False),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_uid"],
            ["pyslc.collection.uid"],
            name=op.f("fk_chat_collection_uid_collection"),
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_chat")),
        schema="pyslc",
    )
    op.create_table(
        "document",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_extension", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_type", sa.String(), nullable=False),
        sa.Column("file_hash", sa.String(), nullable=False),
        sa.Column("collection_uid", sa.UUID(), nullable=False),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_uid"],
            ["pyslc.collection.uid"],
            name=op.f("fk_document_collection_uid_collection"),
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_document")),
        schema="pyslc",
    )
    op.create_table(
        "knowledge",
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("collection_uid", sa.UUID(), nullable=False),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_uid"],
            ["pyslc.collection.uid"],
            name=op.f("fk_knowledge_collection_uid_collection"),
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_knowledge")),
        schema="pyslc",
    )
    op.create_table(
        "message",
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("previous_message_id", sa.UUID(), nullable=True),
        sa.Column("next_message_id", sa.UUID(), nullable=True),
        sa.Column("chat_uid", sa.UUID(), nullable=False),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_uid"], ["pyslc.chat.uid"], name=op.f("fk_message_chat_uid_chat")
        ),
        sa.ForeignKeyConstraint(
            ["next_message_id"],
            ["pyslc.message.uid"],
            name=op.f("fk_message_next_message_id_message"),
        ),
        sa.ForeignKeyConstraint(
            ["previous_message_id"],
            ["pyslc.message.uid"],
            name=op.f("fk_message_previous_message_id_message"),
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_message")),
        schema="pyslc",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message", schema="pyslc")
    op.drop_table("knowledge", schema="pyslc")
    op.drop_table("document", schema="pyslc")
    op.drop_table("chat", schema="pyslc")
    op.drop_index(
        op.f("ix_pyslc_collection_name"), table_name="collection", schema="pyslc"
    )
    op.drop_table("collection", schema="pyslc")
    # ### end Alembic commands ###
