"""empty message

Revision ID: e5e8e29e960d
Revises:
Create Date: 2024-02-05 22:11:06.499970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5e8e29e960d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_deleted", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="pyslc",
    )
    op.create_index(
        op.f("ix_pyslc_collection_name"),
        "collection",
        ["name"],
        unique=True,
        schema="pyslc",
    )
    op.create_table(
        "chat",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_deleted", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["pyslc.collection.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pyslc",
    )
    op.create_table(
        "document",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_extension", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_type", sa.String(), nullable=False),
        sa.Column("file_hash", sa.String(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_deleted", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["pyslc.collection.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pyslc",
    )
    op.create_table(
        "knowledge",
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_deleted", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["pyslc.collection.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pyslc",
    )
    op.create_table(
        "message",
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("previous_message_id", sa.UUID(), nullable=True),
        sa.Column("next_message_id", sa.UUID(), nullable=True),
        sa.Column("chat_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_deleted", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["pyslc.chat.id"],
        ),
        sa.ForeignKeyConstraint(
            ["next_message_id"],
            ["pyslc.message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_message_id"],
            ["pyslc.message.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pyslc",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message", schema="pyslc")
    op.drop_table("knowledge", schema="pyslc")
    op.drop_table("document", schema="pyslc")
    op.drop_table("chat", schema="pyslc")
    op.drop_index(
        op.f("ix_pyslc_collection_name"), table_name="collection", schema="pyslc"
    )
    op.drop_table("collection", schema="pyslc")
    # ### end Alembic commands ###
